apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: coredns
  name: coredns
  namespace: dns-system
spec:
  type: ClusterIP
  externalIPs:
  - 172.22.132.10
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
  - name: dns-udp
    port: 53
    protocol: UDP
  selector:
    k8s-app: coredns
  
