apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: dns-system
data:
  Corefile: |-
    .:53 {
      log . {
        class denial
      }
      cache
      errors
      loadbalance round_robin
      whoami
      health
      prometheus 0.0.0.0:9153
      proxy . 172.17.79.171:53 172.17.79.172:53
    }

    kairen.k8s.ai {
      etcd kairen.k8s.ai {
        stubzones
        path /skydns
        endpoint http://coredns-etcd:2379
        upstream 172.17.79.171:53 172.17.79.172:53
        debug
      }
      errors
      log
    }
